version: '3.8'

services:
  services_hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: services_hub
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - services_network

  # You can uncomment this section if you want to include the weather_api service
  # weather_api:
  #   build:
  #     context: ./api/weather_api
  #     dockerfile: Dockerfile
  #   container_name: weather_api
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped
  #   networks:
  #     - services_network

networks:
  services_network:
    driver: bridge