[project]
name = "services-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi-code-generator>=0.5.4",
    "fastapi[standard]>=0.115.12",
]
