# generated by fastapi-codegen:
#   filename:  merged-api-spec.json
#   timestamp: 2025-05-18T08:28:29+00:00

from __future__ import annotations

from typing import Optional, Union

from fastapi import Query

from .models import (
    AirTemperatureGetResponse,
    AirTemperatureGetResponse1,
    AirTemperatureGetResponse2,
    FourDayOutlookGetResponse,
    FourDayOutlookGetResponse1,
    FourDayOutlookGetResponse2,
    TwentyFourHrForecastGetResponse,
    TwentyFourHrForecastGetResponse1,
    TwentyFourHrForecastGetResponse2,
    TwoHrForecastGetResponse,
    TwoHrForecastGetResponse1,
    TwoHrForecastGetResponse2,
    WeatherGetResponse,
    WeatherGetResponse1,
    WeatherGetResponse2,
    WindDirectionGetResponse,
    WindDirectionGetResponse1,
    WindDirectionGetResponse2,
)
