# coding: utf-8

"""
    Merged API Services

    This is a merged OpenAPI specification containing multiple API services

    The version of the OpenAPI document: 2025.05.17
    Contact: feedback@data.gov.sg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.four_day_outlook_get200_response_data_records_inner_forecasts_inner import FourDayOutlookGet200ResponseDataRecordsInnerForecastsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FourDayOutlookGet200ResponseDataRecordsInner(BaseModel):
    """
    FourDayOutlookGet200ResponseDataRecordsInner
    """ # noqa: E501
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    updated_timestamp: Optional[StrictStr] = Field(default=None, alias="updatedTimestamp")
    timestamp: Optional[StrictStr] = None
    forecasts: Optional[List[FourDayOutlookGet200ResponseDataRecordsInnerForecastsInner]] = Field(default=None, description="Forecast summary for the day")
    __properties: ClassVar[List[str]] = ["date", "updatedTimestamp", "timestamp", "forecasts"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FourDayOutlookGet200ResponseDataRecordsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in forecasts (list)
        _items = []
        if self.forecasts:
            for _item in self.forecasts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['forecasts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FourDayOutlookGet200ResponseDataRecordsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "updatedTimestamp": obj.get("updatedTimestamp"),
            "timestamp": obj.get("timestamp"),
            "forecasts": [FourDayOutlookGet200ResponseDataRecordsInnerForecastsInner.from_dict(_item) for _item in obj.get("forecasts")] if obj.get("forecasts") is not None else None
        })
        return _obj


