# coding: utf-8

"""
    Merged API Services

    This is a merged OpenAPI specification containing multiple API services

    The version of the OpenAPI document: 2025.05.17
    Contact: feedback@data.gov.sg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.twenty_four_hr_forecast_get200_response_data_records_inner_general import TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneral
from openapi_server.models.twenty_four_hr_forecast_get200_response_data_records_inner_periods_inner import TwentyFourHrForecastGet200ResponseDataRecordsInnerPeriodsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TwentyFourHrForecastGet200ResponseDataRecordsInner(BaseModel):
    """
    TwentyFourHrForecastGet200ResponseDataRecordsInner
    """ # noqa: E501
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    updated_timestamp: Optional[StrictStr] = Field(default=None, description="Time of acquisition of data from NEA", alias="updatedTimestamp")
    tiemstamp: Optional[StrictStr] = Field(default=None, description="Time forecast was issued by NEA")
    general: Optional[TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneral] = None
    periods: Optional[List[TwentyFourHrForecastGet200ResponseDataRecordsInnerPeriodsInner]] = Field(default=None, description="Forecasts for various areas in Singapore")
    __properties: ClassVar[List[str]] = ["date", "updatedTimestamp", "tiemstamp", "general", "periods"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TwentyFourHrForecastGet200ResponseDataRecordsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of general
        if self.general:
            _dict['general'] = self.general.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in periods (list)
        _items = []
        if self.periods:
            for _item in self.periods:
                if _item:
                    _items.append(_item.to_dict())
            _dict['periods'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TwentyFourHrForecastGet200ResponseDataRecordsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "updatedTimestamp": obj.get("updatedTimestamp"),
            "tiemstamp": obj.get("tiemstamp"),
            "general": TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneral.from_dict(obj.get("general")) if obj.get("general") is not None else None,
            "periods": [TwentyFourHrForecastGet200ResponseDataRecordsInnerPeriodsInner.from_dict(_item) for _item in obj.get("periods")] if obj.get("periods") is not None else None
        })
        return _obj


