# coding: utf-8

"""
    Merged API Services

    This is a merged OpenAPI specification containing multiple API services

    The version of the OpenAPI document: 2025.05.17
    Contact: feedback@data.gov.sg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.twenty_four_hr_forecast_get200_response_data_records_inner_general_forecast import TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TwentyFourHrForecastGet200ResponseDataRecordsInnerPeriodsInnerRegions(BaseModel):
    """
    TwentyFourHrForecastGet200ResponseDataRecordsInnerPeriodsInnerRegions
    """ # noqa: E501
    west: Optional[TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast] = None
    east: Optional[TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast] = None
    central: Optional[TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast] = None
    north: Optional[TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast] = None
    south: Optional[TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast] = None
    __properties: ClassVar[List[str]] = ["west", "east", "central", "north", "south"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TwentyFourHrForecastGet200ResponseDataRecordsInnerPeriodsInnerRegions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of west
        if self.west:
            _dict['west'] = self.west.to_dict()
        # override the default output from pydantic by calling `to_dict()` of east
        if self.east:
            _dict['east'] = self.east.to_dict()
        # override the default output from pydantic by calling `to_dict()` of central
        if self.central:
            _dict['central'] = self.central.to_dict()
        # override the default output from pydantic by calling `to_dict()` of north
        if self.north:
            _dict['north'] = self.north.to_dict()
        # override the default output from pydantic by calling `to_dict()` of south
        if self.south:
            _dict['south'] = self.south.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TwentyFourHrForecastGet200ResponseDataRecordsInnerPeriodsInnerRegions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "west": TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast.from_dict(obj.get("west")) if obj.get("west") is not None else None,
            "east": TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast.from_dict(obj.get("east")) if obj.get("east") is not None else None,
            "central": TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast.from_dict(obj.get("central")) if obj.get("central") is not None else None,
            "north": TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast.from_dict(obj.get("north")) if obj.get("north") is not None else None,
            "south": TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralForecast.from_dict(obj.get("south")) if obj.get("south") is not None else None
        })
        return _obj


