# coding: utf-8

"""
    Merged API Services

    This is a merged OpenAPI specification containing multiple API services

    The version of the OpenAPI document: 2025.05.17
    Contact: feedback@data.gov.sg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.twenty_four_hr_forecast_get200_response_data_records_inner_general_valid_period import TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralValidPeriod
from openapi_server.models.two_hr_forecast_get200_response_data_items_inner_forecasts_inner import TwoHrForecastGet200ResponseDataItemsInnerForecastsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TwoHrForecastGet200ResponseDataItemsInner(BaseModel):
    """
    TwoHrForecastGet200ResponseDataItemsInner
    """ # noqa: E501
    updated_timestamp: Optional[StrictStr] = Field(default=None, description="Time of acquisition of data from NEA")
    timestamp: Optional[StrictStr] = Field(default=None, description="Time forecast was issued by NEA")
    valid_period: Optional[TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralValidPeriod] = None
    forecasts: Optional[List[TwoHrForecastGet200ResponseDataItemsInnerForecastsInner]] = Field(default=None, description="Forecasts for various areas in Singapore")
    __properties: ClassVar[List[str]] = ["updated_timestamp", "timestamp", "valid_period", "forecasts"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TwoHrForecastGet200ResponseDataItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of valid_period
        if self.valid_period:
            _dict['valid_period'] = self.valid_period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in forecasts (list)
        _items = []
        if self.forecasts:
            for _item in self.forecasts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['forecasts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TwoHrForecastGet200ResponseDataItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "updated_timestamp": obj.get("updated_timestamp"),
            "timestamp": obj.get("timestamp"),
            "valid_period": TwentyFourHrForecastGet200ResponseDataRecordsInnerGeneralValidPeriod.from_dict(obj.get("valid_period")) if obj.get("valid_period") is not None else None,
            "forecasts": [TwoHrForecastGet200ResponseDataItemsInnerForecastsInner.from_dict(_item) for _item in obj.get("forecasts")] if obj.get("forecasts") is not None else None
        })
        return _obj


