# coding: utf-8

"""
    Merged API Services

    This is a merged OpenAPI specification containing multiple API services

    The version of the OpenAPI document: 2025.05.17
    Contact: feedback@data.gov.sg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.wind_direction_get200_response_data_stations_inner_label_location import WindDirectionGet200ResponseDataStationsInnerLabelLocation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WindDirectionGet200ResponseDataStationsInner(BaseModel):
    """
    WindDirectionGet200ResponseDataStationsInner
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Station's ID")
    device_id: Optional[StrictStr] = Field(default=None, description="Reading Device's ID (usually same as Station's ID)", alias="deviceId")
    name: Optional[StrictStr] = Field(default=None, description="Station's name")
    label_location: Optional[WindDirectionGet200ResponseDataStationsInnerLabelLocation] = Field(default=None, alias="labelLocation")
    __properties: ClassVar[List[str]] = ["id", "deviceId", "name", "labelLocation"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WindDirectionGet200ResponseDataStationsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of label_location
        if self.label_location:
            _dict['labelLocation'] = self.label_location.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WindDirectionGet200ResponseDataStationsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "deviceId": obj.get("deviceId"),
            "name": obj.get("name"),
            "labelLocation": WindDirectionGet200ResponseDataStationsInnerLabelLocation.from_dict(obj.get("labelLocation")) if obj.get("labelLocation") is not None else None
        })
        return _obj


